# Generated by Django 4.2.16 on 2026-04-09 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_userprofile_full_name_userprofile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='hourly_rate',
            field=models.DecimalField(decimal_places=2, default=14.15, help_text='Your hourly rate in euros, used to calculate labour cost per product.', max_digits=6),
        ),
    ]
