# Generated by Django 4.2.16 on 2026-02-10 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etsy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='etsytoken',
            name='etsy_user_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
