# Generated by Django 4.2.16 on 2026-04-06 00:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('etsy', '0002_etsytoken_etsy_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='etsytoken',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='etsytoken',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='etsytoken',
            name='etsy_user_id',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='etsytoken',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
