# Generated by Django 4.2.16 on 2026-02-19 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalproductlisting',
            name='shop_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
