# Generated by Django 4.2.16 on 2026-03-11 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_externalproductlisting_shop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalproductlisting',
            name='linked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
