# Generated by Django 4.2.16 on 2026-03-17 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_externalproductlisting_linked_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalproductlisting',
            name='listing_image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
