# Generated by Django 4.2.16 on 2026-03-24 22:42

from django.db import migrations, models

from django.db import migrations, models

def backfill_platforms(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    ExternalProductListing = apps.get_model('products', 'ExternalProductListing')

    for product in Product.objects.all():
        platforms = ["MakerSuite"]
        has_etsy = ExternalProductListing.objects.filter(
            product=product,
            platform="Etsy"
        ).exists()
        if has_etsy:
            platforms.append("Etsy")
        product.platforms = platforms
        product.save(update_fields=["platforms"])

class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_image_url'),
    ]


    operations = [
        migrations.AddField(
            model_name='product',
            name='platforms',
            field=models.JSONField(default=list),
        ),
        migrations.RunPython(backfill_platforms, migrations.RunPython.noop),
    ]
