# Generated by Django 4.2.16 on 2026-04-03 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_add_platforms_to_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='externalproductlisting',
            name='etsy_is_taxable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='externalproductlisting',
            name='etsy_listing_type',
            field=models.CharField(blank=True, default='physical', max_length=50),
        ),
        migrations.AddField(
            model_name='externalproductlisting',
            name='etsy_materials',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='externalproductlisting',
            name='etsy_should_auto_renew',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='externalproductlisting',
            name='etsy_tags',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='externalproductlisting',
            name='etsy_when_made',
            field=models.CharField(blank=True, default='made_to_order', max_length=50),
        ),
        migrations.AddField(
            model_name='externalproductlisting',
            name='etsy_who_made',
            field=models.CharField(blank=True, default='i_did', max_length=50),
        ),
    ]
