# Generated by Django 4.2.16 on 2026-04-03 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_externalproductlisting_etsy_is_taxable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_url',
        ),
        migrations.AddField(
            model_name='externalproductlisting',
            name='internal_image_pushed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='externalproductlisting',
            name='last_pushed_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
