# Generated by Django 4.2.16 on 2026-04-03 06:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_image_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='externalproductlisting',
            name='internal_image_pushed',
        ),
        migrations.RemoveField(
            model_name='externalproductlisting',
            name='last_pushed_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('rank', models.PositiveIntegerField(default=0)),
                ('pushed_to_etsy', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.product')),
            ],
            options={
                'ordering': ['rank', 'created_at'],
            },
        ),
    ]
