# Generated by Django 4.2.16 on 2026-04-12 22:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_saletag_salelog'),
    ]

    operations = [
        migrations.AddField(
            model_name='salelog',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='products.market'),
        ),
    ]
