# Generated by Django 4.2.16 on 2026-04-12 22:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_userprofile_hourly_rate'),
        ('products', '0012_salelog_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salelog',
            name='market',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sale_logs', to='products.market'),
        ),
        migrations.AlterField(
            model_name='salelog',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markets', to='authentication.userprofile'),
        ),
    ]
