# Generated by Django 4.2.16 on 2026-04-14 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_alter_salelog_market_alter_salelog_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='salelog',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
