# Generated by Django 4.2.16 on 2026-04-03 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='tags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
