# Generated by Django 4.2.16 on 2026-03-26 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawmaterial',
            old_name='supplier_url',
            new_name='supplier',
        ),
        migrations.AlterField(
            model_name='make',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
