# Generated by Django 4.2.16 on 2026-03-26 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rename_supplier_url_rawmaterial_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saletag',
            name='color',
        ),
    ]
