# Generated by Django 4.2.16 on 2026-04-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_rawmaterial_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='low_stock_threshold',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True),
        ),
    ]
