# Generated by Django 4.2.16 on 2026-04-09 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_rawmaterial_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='rawmaterial',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
