# Generated by Django 4.2.16 on 2026-03-26 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_rawmaterial_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rawmaterial',
            old_name='unit',
            new_name='unit_type',
        ),
        migrations.RemoveField(
            model_name='make',
            name='completed_at',
        ),
        migrations.RemoveField(
            model_name='make',
            name='status',
        ),
        migrations.AlterField(
            model_name='make',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='supplier',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
