# Generated by Django 4.2.16 on 2026-04-09 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_rawmaterial_sale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='salelog',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='salelog',
            name='unit_prices',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
