# Generated by Django 4.2.16 on 2026-04-10 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_salelog_sale_price_salelog_unit_prices'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rawmaterial',
            name='sale_price',
        ),
        migrations.AddField(
            model_name='makelog',
            name='duration_minutes',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rawmaterial',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='material_photos/'),
        ),
    ]
