# Generated by Django 4.2.16 on 2026-04-10 02:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0009_remove_externalproductlisting_internal_image_pushed_and_more'),
        ('inventory', '0007_remove_rawmaterial_sale_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salelog',
            name='project',
        ),
        migrations.AddField(
            model_name='salelog',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sale_logs', to='products.product'),
            preserve_default=False,
        ),
    ]
