# Generated by Django 4.2.16 on 2026-04-12 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_remove_salelog_project_salelog_product'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='saletag',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='saletag',
            name='owner',
        ),
        migrations.DeleteModel(
            name='SaleLog',
        ),
        migrations.DeleteModel(
            name='SaleTag',
        ),
    ]
