# Generated by Django 4.2.16 on 2026-04-15 06:55

from django.db import migrations, models
import inventory.models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0011_project_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rawmaterial',
            name='custom_fields',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='rawmaterial',
            name='unit_type',
            field=models.CharField(max_length=50, validators=[inventory.models.validate_unit_type]),
        ),
    ]
