# Generated by Django 4.2.16 on 2026-04-29 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_alter_rawmaterial_custom_fields_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='stock_adjustment',
            field=models.IntegerField(default=0),
        ),
    ]
